# ASHBY_COMPANIES = [
#     {"name": "razorpay", "provider": "ashby", "token": "razorpay"},
#     {"name": "cred", "provider": "ashby", "token": "cred"},
#     {"name": "meesho", "provider": "ashby", "token": "meesho"},
#     {"name": "sharechat", "provider": "ashby", "token": "sharechat"},
#     {"name": "groww", "provider": "ashby", "token": "groww"},
#     {"name": "slice", "provider": "ashby", "token": "slice"},
#     {"name": "coinbase", "provider": "ashby", "token": "coinbase"},
#     {"name": "swiggy", "provider": "ashby", "token": "swiggy"},
#     {"name": "zepto", "provider": "ashby", "token": "zepto"},
#     {"name": "urbancompany", "provider": "ashby", "token": "urbancompany"},
# ]


ASHBY_COMPANIES = [
        # ── Fintech / Payments ───────────────────────────────────────────────────
    {"name": "Razorpay",            "provider": "ashby", "hq": "Bengaluru",            "sector": "Fintech/Payments",  "token": "razorpay"},
    {"name": "Open Financial",      "provider": "ashby", "hq": "Bengaluru",            "sector": "NeoBank/BaaS",      "token": "open"},
    {"name": "Niyo Solutions",      "provider": "ashby", "hq": "Bengaluru",            "sector": "NeoBank",           "token": "niyo"},
    {"name": "Progcap",             "provider": "ashby", "hq": "Delhi",                "sector": "Supply Chain Fin.", "token": "progcap"},
    {"name": "Mintifi",             "provider": "ashby", "hq": "Mumbai",               "sector": "Supply Chain Fin.", "token": "mintifi"},
    {"name": "Recur Club",          "provider": "ashby", "hq": "Gurgaon",              "sector": "Revenue Financing", "token": "recurclub"},
    {"name": "Klub",                "provider": "ashby", "hq": "Mumbai/Bengaluru",     "sector": "Revenue Financing", "token": "klub"},
    {"name": "Yubi (CredAvenue)",   "provider": "ashby", "hq": "Chennai/Mumbai",       "sector": "Debt Platform",     "token": "credavenue"},
    {"name": "Oxyzo Financial",     "provider": "ashby", "hq": "Gurgaon",              "sector": "B2B Lending",       "token": "oxyzo"},
    {"name": "ZestMoney",           "provider": "ashby", "hq": "Bengaluru",            "sector": "BNPL/Lending",      "token": "zestmoney"},
    {"name": "Jar App",             "provider": "ashby", "hq": "Bengaluru",            "sector": "Micro-savings",     "token": "jar"},
    {"name": "Freo (MoneyTap)",     "provider": "ashby", "hq": "Bengaluru",            "sector": "Credit Line",       "token": "freo"},
    {"name": "Stashfin",            "provider": "ashby", "hq": "Gurgaon/Delhi",        "sector": "Credit/BNPL",       "token": "stashfin"},
    # ── SaaS / Dev Tools ─────────────────────────────────────────────────────
    {"name": "Spendflo",            "provider": "ashby", "hq": "Chennai",              "sector": "SaaS Procurement",  "token": "spendflo"},
    {"name": "Zluri",               "provider": "ashby", "hq": "Bengaluru",            "sector": "SaaS Management",   "token": "zluri"},
    {"name": "Sprinto",             "provider": "ashby", "hq": "Bengaluru",            "sector": "Compliance SaaS",   "token": "sprinto"},
    {"name": "Scrut Automation",    "provider": "ashby", "hq": "Bengaluru",            "sector": "GRC/Security SaaS", "token": "scrutautomation"},
    {"name": "Kloudle",             "provider": "ashby", "hq": "Bengaluru",            "sector": "Cloud Security",    "token": "kloudle"},
    {"name": "Securden",            "provider": "ashby", "hq": "Chennai",              "sector": "PAM/Cybersecurity", "token": "securden"},
    {"name": "Indusface",           "provider": "ashby", "hq": "Ahmedabad",            "sector": "AppSec SaaS",       "token": "indusface"},
    {"name": "Accops Systems",      "provider": "ashby", "hq": "Pune/Noida",           "sector": "Zero Trust/IAM",    "token": "accops"},
    {"name": "Qusecure",            "provider": "ashby", "hq": "Bengaluru",            "sector": "Cybersecurity",     "token": "qusecure"},
    {"name": "Pixis",               "provider": "ashby", "hq": "Bengaluru",            "sector": "AI Marketing SaaS", "token": "pixis"},
    {"name": "Factors.ai",          "provider": "ashby", "hq": "Bengaluru",            "sector": "Revenue Analytics", "token": "factors"},
    {"name": "Toplyne",             "provider": "ashby", "hq": "Bengaluru",            "sector": "PLG/Revenue SaaS",  "token": "toplyne"},
    {"name": "June.so India",       "provider": "ashby", "hq": "Bengaluru",            "sector": "Product Analytics", "token": "june"},
    {"name": "Suprsend",            "provider": "ashby", "hq": "Bengaluru",            "sector": "Notification Infra","token": "suprsend"},
    {"name": "Fynd (Shopsense)",    "provider": "ashby", "hq": "Mumbai",               "sector": "Retail SaaS",       "token": "fynd"},
    {"name": "DotPe",               "provider": "ashby", "hq": "Gurgaon",              "sector": "Retail/Payments SaaS","token": "dotpe"},
    {"name": "Gofrugal Technologies","provider": "ashby", "hq": "Chennai",             "sector": "Retail ERP SaaS",   "token": "gofrugal"},
    {"name": "Turvo",               "provider": "ashby", "hq": "Bengaluru",            "sector": "Supply Chain SaaS", "token": "turvo"},
    # ── Consumer / Marketplace ───────────────────────────────────────────────
    {"name": "Mfine",               "provider": "ashby", "hq": "Bengaluru",            "sector": "HealthTech/AI",     "token": "mfine"},
    {"name": "Koo App",             "provider": "ashby", "hq": "Bengaluru",            "sector": "Social Media",      "token": "koo"},
    {"name": "ShareChat (Moj)",     "provider": "ashby", "hq": "Bengaluru",            "sector": "Social/Video",      "token": "sharechat"},
    {"name": "Josh (DailyHunt)",    "provider": "ashby", "hq": "Bengaluru",            "sector": "Short Video",       "token": "dailyhunt"},
    {"name": "Glance (InMobi)",     "provider": "ashby", "hq": "Bengaluru",            "sector": "Content Platform",  "token": "glance"},
    {"name": "Classplus",           "provider": "ashby", "hq": "Noida",               "sector": "EdTech SaaS",       "token": "classplus"},
    {"name": "Teachmint",           "provider": "ashby", "hq": "Bengaluru",            "sector": "EdTech Infra",      "token": "teachmint"},
    {"name": "Sunstone Eduversity", "provider": "ashby", "hq": "Noida/Gurgaon",       "sector": "Higher EdTech",     "token": "sunstone"},
    {"name": "Apli Jobs",           "provider": "ashby", "hq": "Mumbai",               "sector": "Blue-collar HR",    "token": "aplijobs"},
    {"name": "WorkIndia",           "provider": "ashby", "hq": "Bengaluru",            "sector": "Blue-collar HR",    "token": "workindia"},
    {"name": "Rocket.Chat India",   "provider": "ashby", "hq": "Bengaluru",            "sector": "Comms SaaS",        "token": "rocketchat"},
    {"name": "BoldDesk (Syncfusion)","provider": "ashby", "hq": "Chennai",             "sector": "Help Desk SaaS",    "token": "bolddesk"},
    {"name": "Rocketlane",          "provider": "ashby", "hq": "Chennai",              "sector": "PSA/Customer Ops",  "token": "rocketlane"},
    {"name": "Plivo",               "provider": "ashby", "hq": "Bengaluru",            "sector": "CPaaS",             "token": "plivo"},
    {"name": "Tata 1mg",            "provider": "ashby", "hq": "Gurgaon",              "sector": "HealthTech/Pharma", "token": "1mg"},
    {"name": "Wellthy Therapeutics","provider": "ashby", "hq": "Mumbai/Bengaluru",     "sector": "DigitalHealth",     "token": "wellthy"},
    {"name": "Medi Assist",         "provider": "ashby", "hq": "Bengaluru",            "sector": "HealthInsurance",   "token": "mediassist"},
    {"name": "Roadcast",            "provider": "ashby", "hq": "Noida",               "sector": "Fleet/GPS Tech",    "token": "roadcast"},
    {"name": "Zetwerk Manufacturing","provider": "ashby", "hq": "Bengaluru",           "sector": "Manufacturing B2B", "token": "zetwerk"},
    {"name": "Probo",               "provider": "ashby", "hq": "Bengaluru",            "sector": "Opinion Trading",   "token": "probo"},
    {"name": "WazirX (Zanmai Labs)", "provider": "ashby", "hq": "Mumbai",              "sector": "Crypto Exchange",   "token": "wazirx"},
    {"name": "CoinDCX",             "provider": "ashby", "hq": "Mumbai",               "sector": "Crypto Exchange",   "token": "coindcx"},
    {"name": "Mudrex",              "provider": "ashby", "hq": "Bengaluru",            "sector": "Crypto/WealthTech", "token": "mudrex"},
    {"name": "Traya Health",        "provider": "ashby", "hq": "Mumbai",               "sector": "D2C HealthTech",    "token": "traya"},
    
]