GREENHOUSE_COMPANIES = [
        {"name": "Razorpay",            "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Fintech/Payments",  "token": "razorpay"},
    {"name": "Navi Technologies",   "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Fintech/Lending",   "token": "navitechnologies"},
    {"name": "Indifi Technologies", "provider": "greenhouse", "hq": "Gurgaon",         "sector": "SME Lending",       "token": "indifi"},
    {"name": "KreditBee",           "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Fintech/Credit",    "token": "kreditbee"},
    {"name": "Axio (Capital Float)", "provider": "greenhouse", "hq": "Bengaluru",      "sector": "Fintech/BNPL",      "token": "axio"},
    {"name": "BharatPe",            "provider": "greenhouse", "hq": "Delhi/Gurgaon",   "sector": "Fintech/Payments",  "token": "bharatpe"},
    {"name": "MobiKwik",            "provider": "greenhouse", "hq": "Gurgaon",         "sector": "Fintech/Wallet",    "token": "mobikwik"},
    {"name": "Freecharge (Axis)",   "provider": "greenhouse", "hq": "Gurgaon",         "sector": "Fintech",           "token": "freecharge"},
    {"name": "Cashfree Payments",   "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Payments API",      "token": "cashfree"},
    {"name": "PayU India",          "provider": "greenhouse", "hq": "Gurgaon",         "sector": "Payments",          "token": "payu"},
    {"name": "Perfios",             "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Fintech/Analytics", "token": "perfios"},
    {"name": "Lendingkart",         "provider": "greenhouse", "hq": "Ahmedabad",       "sector": "SME Lending",       "token": "lendingkart"},
    {"name": "Faircent",            "provider": "greenhouse", "hq": "Gurgaon",         "sector": "P2P Lending",       "token": "faircent"},
    {"name": "i2iFunding",          "provider": "greenhouse", "hq": "Noida",           "sector": "P2P Lending",       "token": "i2ifunding"},
    {"name": "Fincash",             "provider": "greenhouse", "hq": "Mumbai",          "sector": "WealthTech",        "token": "fincash"},
    # ── SaaS / B2B Tech ─────────────────────────────────────────────────────
    {"name": "Zoho Corporation",    "provider": "greenhouse", "hq": "Chennai/Delhi",   "sector": "Business SaaS",     "token": "zoho"},
    {"name": "Druva",               "provider": "greenhouse", "hq": "Pune/Bengaluru",  "sector": "Cloud Backup SaaS", "token": "druva"},
    {"name": "Icertis",             "provider": "greenhouse", "hq": "Pune/Noida",      "sector": "Contract SaaS",     "token": "icertis"},
    {"name": "Haptik (Jio)",        "provider": "greenhouse", "hq": "Mumbai",          "sector": "Conversational AI", "token": "haptik"},
    {"name": "Yellow.ai",           "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Conversational AI", "token": "yellowai"},
    {"name": "Whatfix",             "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Digital Adoption",  "token": "whatfix"},
    {"name": "Leadsquared",         "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Sales CRM SaaS",    "token": "leadsquared"},
    {"name": "Capillary Technologies", "provider": "greenhouse", "hq": "Bengaluru/Gurgaon","sector": "Loyalty SaaS",  "token": "capillary"},
    {"name": "Netcore Cloud",       "provider": "greenhouse", "hq": "Mumbai",          "sector": "MarTech SaaS",      "token": "netcore"},
    {"name": "Mindtickle",          "provider": "greenhouse", "hq": "Pune/SF",         "sector": "Sales Enablement",  "token": "mindtickle"},
    {"name": "Salesken.ai",         "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Sales AI",          "token": "salesken"},
    {"name": "Vymo",                "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Sales SaaS",        "token": "vymo"},
    {"name": "Exotel",              "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Cloud Comms SaaS",  "token": "exotel"},
    {"name": "Kaleyra",             "provider": "greenhouse", "hq": "Bengaluru",       "sector": "CPaaS",             "token": "kaleyra"},
    {"name": "Gupshup",             "provider": "greenhouse", "hq": "Bengaluru/SF",    "sector": "CPaaS/Messaging",   "token": "gupshup"},
    {"name": "Ameyo (Exotel)",      "provider": "greenhouse", "hq": "Gurgaon",         "sector": "Contact Center SaaS","token": "ameyo"},
    {"name": "Ozonetel",            "provider": "greenhouse", "hq": "Hyderabad",       "sector": "Cloud Telephony",   "token": "ozonetel"},
    {"name": "Freshdesk (Freshworks)","provider": "greenhouse","hq": "Chennai",         "sector": "Customer SaaS",     "token": "freshdesk"},
    {"name": "Helpshift",           "provider": "greenhouse", "hq": "Mumbai/Bengaluru","sector": "Customer Support AI","token": "helpshift"},
    {"name": "Zendesk India",       "provider": "greenhouse", "hq": "Bengaluru",       "sector": "CX SaaS",           "token": "zendesk"},
    # ── EdTech ──────────────────────────────────────────────────────────────
    {"name": "BYJU'S",              "provider": "greenhouse", "hq": "Bengaluru",       "sector": "EdTech",            "token": "byjus"},
    {"name": "Toppr (BYJU'S)",      "provider": "greenhouse", "hq": "Mumbai",          "sector": "EdTech",            "token": "toppr"},
    {"name": "Testbook",            "provider": "greenhouse", "hq": "Mumbai/Noida",    "sector": "EdTech/Gov Exams",  "token": "testbook"},
    {"name": "CollegeDunia",        "provider": "greenhouse", "hq": "Gurgaon",         "sector": "EdTech/Discovery",  "token": "collegedunia"},
    {"name": "Shiksha.com",         "provider": "greenhouse", "hq": "Noida",           "sector": "EdTech/Discovery",  "token": "shiksha"},
    {"name": "Doubtnut",            "provider": "greenhouse", "hq": "Noida/Gurgaon",   "sector": "EdTech",            "token": "doubtnut"},
    {"name": "PW (Physics Wallah)", "provider": "greenhouse", "hq": "Noida",           "sector": "EdTech",            "token": "physicswallah"},
    {"name": "Adda247",             "provider": "greenhouse", "hq": "Noida",           "sector": "EdTech/Gov Exams",  "token": "adda247"},
    # ── HealthTech ──────────────────────────────────────────────────────────
    {"name": "1mg (Tata Health)",   "provider": "greenhouse", "hq": "Gurgaon",         "sector": "HealthTech/Pharma", "token": "1mg"},
    {"name": "Practo",              "provider": "greenhouse", "hq": "Bengaluru",       "sector": "HealthTech",        "token": "practo"},
    {"name": "Pharmeasy",           "provider": "greenhouse", "hq": "Mumbai",          "sector": "HealthTech/Pharma", "token": "pharmeasy"},
    {"name": "Netmeds (Reliance)",  "provider": "greenhouse", "hq": "Chennai",         "sector": "HealthTech/Pharma", "token": "netmeds"},
    {"name": "Curefit (Cult.fit)",  "provider": "greenhouse", "hq": "Bengaluru",       "sector": "HealthTech/Fitness","token": "curefit"},
    {"name": "Niramai",             "provider": "greenhouse", "hq": "Bengaluru",       "sector": "HealthTech/AI",     "token": "niramai"},
    # ── Logistics / Supply Chain ────────────────────────────────────────────
    {"name": "Rivigo",              "provider": "greenhouse", "hq": "Gurgaon",         "sector": "Logistics Tech",    "token": "rivigo"},
    {"name": "BlackBuck",           "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Logistics Tech",    "token": "blackbuck"},
    {"name": "Porter",              "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Urban Logistics",   "token": "porter"},
    {"name": "Shadowfax",           "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Last-mile Logistics","token": "shadowfax"},
    {"name": "Loadshare",           "provider": "greenhouse", "hq": "Bengaluru",       "sector": "Logistics Network", "token": "loadshare"},
    # ── Consumer Internet / Marketplace ─────────────────────────────────────
    {"name": "Nykaa",               "provider": "greenhouse", "hq": "Mumbai/Delhi",    "sector": "D2C/eCommerce",     "token": "nykaa"},
    {"name": "Snapdeal",            "provider": "greenhouse", "hq": "Gurgaon",         "sector": "eCommerce",         "token": "snapdeal"},
    {"name": "Pepperfry",           "provider": "greenhouse", "hq": "Mumbai",          "sector": "Furniture eComm",   "token": "pepperfry"},
    {"name": "Urban Ladder (Reliance)", "provider": "greenhouse", "hq": "Bengaluru",   "sector": "Furniture eComm",   "token": "urbanladder"},
    {"name": "Lenskart",            "provider": "greenhouse", "hq": "Faridabad/Gurgaon","sector": "D2C Eyewear",      "token": "lenskart"},
    {"name": "Mamaearth (Honasa)",  "provider": "greenhouse", "hq": "Gurgaon",         "sector": "D2C FMCG",          "token": "mamaearth"},
    {"name": "BoAt Lifestyle",      "provider": "greenhouse", "hq": "Delhi/Gurgaon",   "sector": "Consumer Electronics","token": "boat"},
    {"name": "Noise",               "provider": "greenhouse", "hq": "Gurgaon",         "sector": "Consumer Electronics","token": "noise"},
    {"name": "Wakefit",             "provider": "greenhouse", "hq": "Bengaluru",       "sector": "D2C Furniture",     "token": "wakefit"},
    {"name": "Purplle",             "provider": "greenhouse", "hq": "Mumbai",          "sector": "D2C Beauty",        "token": "purplle"},
    {"name": "DealShare",           "provider": "greenhouse", "hq": "Jaipur/Bengaluru","sector": "Social Commerce",   "token": "dealshare"},
    
]