LEVER_COMPANIES = [
    {"name": "zomato", "provider": "lever", "token": "zomato"},
    {"name": "Zomato",              "provider": "lever", "hq": "Gurgaon",             "sector": "Food Tech",         "token": "zomato"},
    {"name": "Swiggy",              "provider": "lever", "hq": "Bengaluru",           "sector": "Food Tech",         "token": "swiggy"},
    {"name": "CRED",                "provider": "lever", "hq": "Bengaluru",           "sector": "Fintech",           "token": "dreamplug"},
    {"name": "Groww",               "provider": "lever", "hq": "Bengaluru",           "sector": "WealthTech",        "token": "groww"},
    {"name": "Zepto",               "provider": "lever", "hq": "Mumbai",              "sector": "Q-Commerce",        "token": "zepto"},
    {"name": "PhonePe",             "provider": "lever", "hq": "Bengaluru",           "sector": "Fintech/Payments",  "token": "phonepe"},
    {"name": "Meesho",              "provider": "lever", "hq": "Bengaluru",           "sector": "Social Commerce",   "token": "meesho"},
    {"name": "BrowserStack",        "provider": "lever", "hq": "Mumbai",              "sector": "Dev Tools/SaaS",    "token": "browserstack"},
    {"name": "Postman",             "provider": "lever", "hq": "Bengaluru/SF",        "sector": "Dev Tools/SaaS",    "token": "postman"},
    {"name": "Chargebee",           "provider": "lever", "hq": "Chennai/SF",          "sector": "Billing SaaS",      "token": "chargebee"},
    {"name": "Freshworks",          "provider": "lever", "hq": "Chennai/Bengaluru",  "sector": "CRM/SaaS",          "token": "freshworks"},
    {"name": "Unacademy",           "provider": "lever", "hq": "Bengaluru",           "sector": "EdTech",            "token": "unacademy"},
    {"name": "Vedantu",             "provider": "lever", "hq": "Bengaluru",           "sector": "EdTech",            "token": "vedantu"},
    {"name": "Dunzo",               "provider": "lever", "hq": "Bengaluru/Gurgaon",  "sector": "Q-Commerce",        "token": "dunzo"},
    {"name": "Shiprocket",          "provider": "lever", "hq": "Delhi",               "sector": "Logistics Tech",    "token": "shiprocket"},
    {"name": "Delhivery",           "provider": "lever", "hq": "Gurgaon",             "sector": "Logistics Tech",    "token": "delhivery"},
    {"name": "Ecom Express",        "provider": "lever", "hq": "Gurgaon",             "sector": "Logistics Tech",    "token": "ecomexpress"},
    {"name": "Udaan",               "provider": "lever", "hq": "Bengaluru",           "sector": "B2B Commerce",      "token": "udaan"},
    {"name": "Slice (Quadrillion)", "provider": "lever", "hq": "Bengaluru",           "sector": "Fintech/Credit",    "token": "sliceit"},
    {"name": "Jupiter Money",       "provider": "lever", "hq": "Bengaluru",           "sector": "NeoBank",           "token": "jupitermoney"},
    {"name": "Fi Money",            "provider": "lever", "hq": "Bengaluru",           "sector": "NeoBank",           "token": "epifi"},
    {"name": "Smallcase",           "provider": "lever", "hq": "Bengaluru",           "sector": "WealthTech",        "token": "smallcase"},
    {"name": "Khatabook",           "provider": "lever", "hq": "Bengaluru",           "sector": "SME Fintech",       "token": "khatabook"},
    {"name": "OkCredit",            "provider": "lever", "hq": "Bengaluru",           "sector": "SME Fintech",       "token": "okcredit"},
    {"name": "Licious",             "provider": "lever", "hq": "Bengaluru",           "sector": "D2C/FoodTech",      "token": "licious"},
    {"name": "Ninjacart",           "provider": "lever", "hq": "Bengaluru",           "sector": "AgriTech/B2B",      "token": "ninjacart"},
    {"name": "DeHaat",              "provider": "lever", "hq": "Gurgaon/Bihar",       "sector": "AgriTech",          "token": "dehaat"},
    {"name": "Zetwerk",             "provider": "lever", "hq": "Bengaluru",           "sector": "Manufacturing B2B", "token": "zetwerk"},
    {"name": "Stanza Living",       "provider": "lever", "hq": "Gurgaon",             "sector": "PropTech",          "token": "stanzaliving"},
    {"name": "NoBroker",            "provider": "lever", "hq": "Bengaluru",           "sector": "PropTech",          "token": "nobroker"},
    {"name": "Spinny",              "provider": "lever", "hq": "Gurgaon",             "sector": "Auto Commerce",     "token": "spinny"},
    {"name": "Cars24",              "provider": "lever", "hq": "Gurgaon",             "sector": "Auto Commerce",     "token": "cars24"},
    {"name": "CarDekho",            "provider": "lever", "hq": "Jaipur/Gurgaon",     "sector": "Auto Tech",         "token": "cardekho"},
    {"name": "OLX India",           "provider": "lever", "hq": "Gurgaon",             "sector": "Classifieds/Tech",  "token": "olx"},
    {"name": "InMobi",              "provider": "lever", "hq": "Bengaluru",           "sector": "AdTech",            "token": "inmobi"},
    {"name": "CleverTap",           "provider": "lever", "hq": "Mumbai/Bengaluru",    "sector": "MarTech SaaS",      "token": "clevertap"},
    {"name": "Appsflyer India",     "provider": "lever", "hq": "Bengaluru",           "sector": "MarTech Analytics", "token": "appsflyer"},
    {"name": "Hasura",              "provider": "lever", "hq": "Bengaluru",           "sector": "Dev Tools/API",     "token": "hasura"},
    {"name": "Setu (Pine Labs)",    "provider": "lever", "hq": "Bengaluru",           "sector": "API/Fintech",       "token": "setu"},
    {"name": "Decentro",            "provider": "lever", "hq": "Bengaluru",           "sector": "BaaS/Fintech",      "token": "decentro"},
    {"name": "Signzy",              "provider": "lever", "hq": "Bengaluru",           "sector": "Fintech/KYC",       "token": "signzy"},
    {"name": "Hyperverge",          "provider": "lever", "hq": "Bengaluru",           "sector": "AI/KYC",            "token": "hyperverge"},
    {"name": "Meritto (NoPaperForms)", "provider": "lever", "hq": "Noida",            "sector": "EdTech SaaS",       "token": "nopaperforms"},
    {"name": "Leap Finance",        "provider": "lever", "hq": "Bengaluru/Delhi",     "sector": "EdFinTech",         "token": "leapfinance"},
    {"name": "upGrad",              "provider": "lever", "hq": "Mumbai/Gurgaon",      "sector": "EdTech",            "token": "upgrad"},
    {"name": "Simplilearn",         "provider": "lever", "hq": "Bengaluru",           "sector": "EdTech/Upskilling", "token": "simplilearn"},
    {"name": "Scaler Academy",      "provider": "lever", "hq": "Bengaluru",           "sector": "EdTech",            "token": "scaler"},
    {"name": "Apna",                "provider": "lever", "hq": "Bengaluru",           "sector": "HR Tech/Jobs",      "token": "apna"},
    {"name": "iimjobs / Hirist",    "provider": "lever", "hq": "Noida",               "sector": "HR Tech",           "token": "iimjobs"},
    {"name": "Darwinbox",           "provider": "lever", "hq": "Hyderabad",           "sector": "HCM SaaS",          "token": "darwinbox"},
    {"name": "Keka HR",             "provider": "lever", "hq": "Hyderabad",           "sector": "HCM SaaS",          "token": "kekahr"},
    {"name": "HRMantra",            "provider": "lever", "hq": "Mumbai",              "sector": "HCM SaaS",          "token": "hrmantra"},
    {"name": "Sprinklr India",      "provider": "lever", "hq": "Gurgaon",             "sector": "CXM SaaS",          "token": "sprinklr"},
    {"name": "HealthifyMe",         "provider": "lever", "hq": "Bengaluru",           "sector": "HealthTech",        "token": "healthifyme"},
    {"name": "Pristyn Care",        "provider": "lever", "hq": "Gurgaon",             "sector": "HealthTech",        "token": "pristyncare"},
    {"name": "Innovaccer",          "provider": "lever", "hq": "Noida",               "sector": "HealthTech/Data",   "token": "innovaccer"},
    {"name": "MediBuddy",           "provider": "lever", "hq": "Bengaluru",           "sector": "HealthTech",        "token": "medibuddy"},
    {"name": "Portea Medical",      "provider": "lever", "hq": "Bengaluru",           "sector": "HealthTech",        "token": "portea"},
    {"name": "Lybrate",             "provider": "lever", "hq": "Gurgaon",             "sector": "HealthTech",        "token": "lybrate"},
    {"name": "Dozee (Turtle Shell)", "provider": "lever", "hq": "Bengaluru",          "sector": "HealthTech/IoT",    "token": "turtleshell"},
]
