WORKDAY_COMPANIES = [
{"name": "Dell Technologies",       "provider": "workday", "hq": "Bengaluru/Hyderabad", "sector": "Hardware/Cloud",    "base_url": "https://dell.wd1.myworkdayjobs.com/External"},
    {"name": "Salesforce",              "provider": "workday", "hq": "Hyderabad/Bengaluru", "sector": "CRM/SaaS",          "base_url": "https://salesforce.wd12.myworkdayjobs.com/Careers"},
    {"name": "Adobe",                   "provider": "workday", "hq": "Noida/Bengaluru",     "sector": "SaaS/Creative",     "base_url": "https://adobe.wd5.myworkdayjobs.com/external_experienced"},
    {"name": "Workday India",           "provider": "workday", "hq": "Bengaluru",            "sector": "HCM SaaS",          "base_url": "https://workday.wd5.myworkdayjobs.com/Workday"},
    {"name": "SAP Labs India",          "provider": "workday", "hq": "Bengaluru/Gurgaon",   "sector": "Enterprise SaaS",   "base_url": "https://sap.wd3.myworkdayjobs.com/SAP"},
    {"name": "Mastercard",              "provider": "workday", "hq": "Pune/Gurgaon",         "sector": "Fintech/Payments",  "base_url": "https://mastercard.wd1.myworkdayjobs.com/CorporateCareers"},
    {"name": "American Express",        "provider": "workday", "hq": "Gurgaon",              "sector": "Fintech/Payments",  "base_url": "https://aexp.wd5.myworkdayjobs.com/amex_experienced_en"},
    {"name": "Visa Inc.",               "provider": "workday", "hq": "Bengaluru/Gurgaon",   "sector": "Fintech/Payments",  "base_url": "https://visa.wd5.myworkdayjobs.com/visa_careers"},
    {"name": "Honeywell India",         "provider": "workday", "hq": "Hyderabad/Noida",      "sector": "Industrial Tech",   "base_url": "https://careers.honeywell.com/us/en"},
    {"name": "Amdocs",                  "provider": "workday", "hq": "Gurgaon/Pune",         "sector": "Telecom Tech",      "base_url": "https://amdocs.wd5.myworkdayjobs.com/Amdocs"},
    {"name": "Zebra Technologies",      "provider": "workday", "hq": "Bengaluru/Noida",      "sector": "IoT/Hardware",      "base_url": "https://zebra.wd1.myworkdayjobs.com/Zebra"},
    {"name": "Concentrix",              "provider": "workday", "hq": "Gurgaon/Noida",        "sector": "IT Services",       "base_url": "https://concentrix.wd5.myworkdayjobs.com/External"},
    {"name": "Conduent",                "provider": "workday", "hq": "Hyderabad/Noida",      "sector": "BPO/Tech",          "base_url": "https://conduent.wd5.myworkdayjobs.com/External"},
    {"name": "DXC Technology",          "provider": "workday", "hq": "Noida/Bengaluru",      "sector": "IT Services",       "base_url": "https://dxc.wd1.myworkdayjobs.com/DXCJobsGlobal"},
    {"name": "Wolters Kluwer",          "provider": "workday", "hq": "Noida/Pune",           "sector": "Legal/Tax SaaS",    "base_url": "https://wolterskluwer.wd5.myworkdayjobs.com/External"},
    {"name": "Aptiv",                   "provider": "workday", "hq": "Hyderabad",            "sector": "Auto Tech",         "base_url": "https://aptiv.wd5.myworkdayjobs.com/Aptiv"},
    {"name": "Verint Systems",          "provider": "workday", "hq": "Hyderabad/Bengaluru", "sector": "AI/Analytics",      "base_url": "https://verint.wd1.myworkdayjobs.com/External"},
    {"name": "Fiserv",                  "provider": "workday", "hq": "Bengaluru/Hyderabad", "sector": "Fintech",           "base_url": "https://fiserv.wd5.myworkdayjobs.com/associates"},
    {"name": "Broadridge Financial",    "provider": "workday", "hq": "Hyderabad/Mumbai",    "sector": "Fintech",           "base_url": "https://broadridge.wd5.myworkdayjobs.com/en-US/careers"},
    {"name": "Synchrony",               "provider": "workday", "hq": "Hyderabad/Bengaluru", "sector": "Fintech",           "base_url": "https://synchrony.wd5.myworkdayjobs.com/ExternalSite"},
    # ── Indian Conglomerates & Large IT ──────────────────────────────────────
    {"name": "Wipro",                   "provider": "workday", "hq": "Bengaluru/Delhi NCR",  "sector": "IT Services",       "base_url": "https://wipro.wd3.myworkdayjobs.com/External"},
    {"name": "HCL Technologies",        "provider": "workday", "hq": "Noida/Gurgaon",        "sector": "IT Services",       "base_url": "https://hcl.wd3.myworkdayjobs.com/HCLTech_Careers"},
    {"name": "Tech Mahindra",           "provider": "workday", "hq": "Pune/Noida/Gurgaon",  "sector": "IT Services",       "base_url": "https://techmahindra.wd3.myworkdayjobs.com/TechMahindra"},
    {"name": "Mphasis",                 "provider": "workday", "hq": "Bengaluru/Noida",      "sector": "IT Services",       "base_url": "https://mphasis.wd5.myworkdayjobs.com/Careers"},
    {"name": "Hexaware Technologies",   "provider": "workday", "hq": "Mumbai/Noida",         "sector": "IT Services",       "base_url": "https://hexaware.wd3.myworkdayjobs.com/Hexaware_Careers"},
    {"name": "Birlasoft",               "provider": "workday", "hq": "Noida",                "sector": "IT Services",       "base_url": "https://birlasoft.wd3.myworkdayjobs.com/Birlasoft_Careers"},
    {"name": "NIIT Technologies",       "provider": "workday", "hq": "Noida/Gurgaon",        "sector": "IT Services",       "base_url": "https://niit.wd3.myworkdayjobs.com/Careers"},
    {"name": "Cyient",                  "provider": "workday", "hq": "Hyderabad",            "sector": "Engineering/IT",    "base_url": "https://cyient.wd3.myworkdayjobs.com/External"},
    {"name": "Persistent Systems",      "provider": "workday", "hq": "Pune/Noida",           "sector": "IT Services",       "base_url": "https://persistent.wd5.myworkdayjobs.com/persistent"},
    {"name": "Mastek",                  "provider": "workday", "hq": "Mumbai/Noida",         "sector": "IT Consulting",     "base_url": "https://mastek.wd3.myworkdayjobs.com/Mastek_Careers"},
    # ── Product / Internet Companies ──────────────────────────────────────────
    {"name": "Paytm (One97 Communications)", "provider": "workday", "hq": "Noida",           "sector": "Fintech",           "base_url": "https://one97.wd3.myworkdayjobs.com/Paytm"},
    {"name": "MakeMyTrip",              "provider": "workday", "hq": "Gurgaon",              "sector": "Travel Tech",       "base_url": "https://makemytrip.wd3.myworkdayjobs.com/Careers"},
    {"name": "Info Edge (Naukri)",      "provider": "workday", "hq": "Noida",                "sector": "HR Tech/Internet",  "base_url": "https://infoedge.wd3.myworkdayjobs.com/InfoEdge"},
    {"name": "Just Dial",               "provider": "workday", "hq": "Mumbai/Bengaluru",     "sector": "Local Search/SaaS", "base_url": "https://justdial.wd3.myworkdayjobs.com/Careers"},
    {"name": "IndiaMART",               "provider": "workday", "hq": "Noida",                "sector": "B2B eCommerce",     "base_url": "https://indiamart.wd3.myworkdayjobs.com/Careers"},
    {"name": "IndiGo (InterGlobe)",     "provider": "workday", "hq": "Gurgaon",              "sector": "Aviation Tech",     "base_url": "https://interglobe.wd3.myworkdayjobs.com/IndiGo_Careers"},
    {"name": "Tata Consultancy Services (TCS)", "provider": "workday", "hq": "Pan India",    "sector": "IT Services",       "base_url": "https://tcs.wd3.myworkdayjobs.com/TCS"},
    {"name": "Infosys BPM",             "provider": "workday", "hq": "Bengaluru/Noida",      "sector": "IT/BPO",            "base_url": "https://infosysbpm.wd3.myworkdayjobs.com/Careers"},
    {"name": "HCL Software",            "provider": "workday", "hq": "Noida",                "sector": "Enterprise SaaS",   "base_url": "https://hclsoftware.wd3.myworkdayjobs.com/Careers"},
    {"name": "Nucleus Software",        "provider": "workday", "hq": "Noida",                "sector": "Fintech/Banking",   "base_url": "https://nucleussoftware.wd3.myworkdayjobs.com/Careers"},
    {"name": "Newgen Software",         "provider": "workday", "hq": "Noida",                "sector": "BPM/Enterprise",    "base_url": "https://newgen.wd3.myworkdayjobs.com/Careers"},
    {"name": "MoEngage",                "provider": "workday", "hq": "Bengaluru/Delhi",      "sector": "MarTech SaaS",      "base_url": "https://moengage.wd5.myworkdayjobs.com/Careers"},
    {"name": "Nagarro",                 "provider": "workday", "hq": "Gurgaon",              "sector": "Digital Engineering","base_url": "https://nagarro.wd3.myworkdayjobs.com/Nagarro"},
    {"name": "Xchanging (DXC)",         "provider": "workday", "hq": "Noida/Bengaluru",      "sector": "IT Services",       "base_url": "https://dxc.wd1.myworkdayjobs.com/DXCJobsGlobal"},
    {"name": "Publicis Sapient",        "provider": "workday", "hq": "Gurgaon/Noida",        "sector": "Digital Consulting","base_url": "https://sapient.wd5.myworkdayjobs.com/Careers"},
    {"name": "GlobalLogic (Hitachi)",   "provider": "workday", "hq": "Noida/Hyderabad",      "sector": "Product Engineering","base_url": "https://globallogic.wd1.myworkdayjobs.com/GlobalLogic"},
    {"name": "Cognizant",               "provider": "workday", "hq": "Hyderabad/Noida",      "sector": "IT Services",       "base_url": "https://cognizant.wd5.myworkdayjobs.com/Cognizant_Careers"},
    {"name": "Capgemini India",         "provider": "workday", "hq": "Mumbai/Noida/Bengaluru","sector": "IT Consulting",    "base_url": "https://capgemini.wd3.myworkdayjobs.com/Capgemini_Careers"},
    {"name": "Accenture India",         "provider": "workday", "hq": "Gurgaon/Bengaluru",   "sector": "IT Consulting",     "base_url": "https://accenture.wd3.myworkdayjobs.com/Accenture_Careers"},
    {"name": "IBM India",               "provider": "workday", "hq": "Bengaluru/Noida",      "sector": "IT/Cloud",          "base_url": "https://ibm.wd12.myworkdayjobs.com/External"},
    {"name": "NTT DATA India",          "provider": "workday", "hq": "Bengaluru/Delhi",      "sector": "IT Services",       "base_url": "https://nttdata.wd3.myworkdayjobs.com/Careers"},
    {"name": "Mindtree (LTIMindtree)",  "provider": "workday", "hq": "Bengaluru/Noida",      "sector": "IT Services",       "base_url": "https://ltimindtree.wd3.myworkdayjobs.com/Careers"},
    {"name": "Mitel Networks",          "provider": "workday", "hq": "Noida",                "sector": "Communication Tech","base_url": "https://mitel.wd5.myworkdayjobs.com/MitelCareers"},
    {"name": "Siemens India",           "provider": "workday", "hq": "Noida/Bengaluru",      "sector": "Industrial Tech",   "base_url": "https://siemens.wd3.myworkdayjobs.com/Siemens_Careers"},
    {"name": "Bosch India",             "provider": "workday", "hq": "Bengaluru/Noida",      "sector": "Auto/IoT Tech",     "base_url": "https://bosch.wd3.myworkdayjobs.com/Bosch_Careers"},
    {"name": "Tata Motors",             "provider": "workday", "hq": "Mumbai/Pune",          "sector": "Auto Tech",         "base_url": "https://tatamotors.wd3.myworkdayjobs.com/Careers"},
    {"name": "L&T Technology Services", "provider": "workday", "hq": "Noida/Bengaluru",      "sector": "Engineering R&D",   "base_url": "https://ltts.wd3.myworkdayjobs.com/LTTS_Careers"},
    {"name": "KPIT Technologies",       "provider": "workday", "hq": "Pune/Noida",           "sector": "Auto/Embedded Tech","base_url": "https://kpit.wd3.myworkdayjobs.com/Careers"},
    {"name": "Coforge (NIIT Tech)",     "provider": "workday", "hq": "Noida",                "sector": "IT Services",       "base_url": "https://coforge.wd3.myworkdayjobs.com/Careers"},
    {"name": "EXL Service",             "provider": "workday", "hq": "Noida/Delhi",          "sector": "Analytics/BPO",     "base_url": "https://exlservice.wd5.myworkdayjobs.com/Careers"},
    {"name": "WNS Global Services",     "provider": "workday", "hq": "Mumbai/Gurgaon",       "sector": "BPO/Analytics",     "base_url": "https://wns.wd3.myworkdayjobs.com/WNS_Careers"},
    {"name": "Genpact",                 "provider": "workday", "hq": "Noida/Gurgaon",        "sector": "BPO/Analytics",     "base_url": "https://genpact.wd5.myworkdayjobs.com/Careers"},
]
